Update artibrage.yml

diff --git a/.github/workflows/artibrage.yml b/.github/workflows/artibrage.yml
--- a/.github/workflows/artibrage.yml
+++ b/.github/workflows/artibrage.yml
@@ -49,6 +49,11 @@ jobs:
               echo "Error: The price difference for ANGELONE exceeds 115!"
               exit 1
             fi
+
+             if [[ "$STOCK" == "NSE:ANGELONE" && $(echo "$DIFFERENCE >= 140" | bc -l) -eq 1 ]]; then
+              echo "Error: The price difference for ANGELONE exceeds 140!"
+              exit 1
+            fi
             
             if [[ "$STOCK" == "NSE:IREDA" && $(echo "$DIFFERENCE <= 10.50" | bc -l) -eq 1 ]]; then
               echo "Error: The price difference for IREDA is less than 10.50!"
